# Generated by Django 3.0.9 on 2020-08-07 20:17

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=120, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=api.models.scramble_uploaded_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_list', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(unique=True), blank=True, null=True, size=None)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLinkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(unique=True)),
                ('product_price_curr', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('product_price_prev', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_link_price', to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Product')),
            ],
        ),
    ]
