# Generated by Django 3.0.9 on 2020-08-07 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(unique=True), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Wishlist_item',
        ),
    ]
