# Generated by Django 3.0.8 on 2020-07-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='API',
        ),
    ]
