# Generated by Django 3.0.8 on 2020-07-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200719_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
