# Generated by Django 3.0.8 on 2020-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
