# Generated by Django 3.0.8 on 2020-07-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200725_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinkprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_link_price', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='productlinkprice',
            name='product_url',
            field=models.URLField(unique=True),
        ),
    ]
