# Generated by Django 3.0.8 on 2020-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200804_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
