# Generated by Django 3.0.8 on 2020-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlinkprice',
            old_name='product_price',
            new_name='product_price_curr',
        ),
        migrations.AddField(
            model_name='productlinkprice',
            name='product_price_prev',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
