# Generated by Django 3.0.8 on 2020-08-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200804_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist_item',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
