FROM python:3.7

# To enable logging
ENV PYTHONUNBUFFERED=1

# Create server directory
RUN mkdir /backend
WORKDIR /backend

# Bundle the source
COPY . ./
RUN chmod +x ./wait.sh

# # install psycopg2 dependencies
# RUN apk update \
#     && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
COPY requirements.txt /backend
RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt

CMD ./wait.sh db 5432 \\
    && ./wait.sh backend 8000 \\
    && ./wait.sh rabbitmq 5672 \\
    && ./wait.sh scrapy 6800 \\
    && celery -A backend beat -l info
